// generated by tools/gen_plugin_names.py; do not edit
#pragma once
#include <cstdint>

// [set][state]: sets x1 pink, x2 orange, x3 green, x4 purple, star power blue; states off, half, lit
static const uint32_t kLights[5][3] = {
	{ 0xee4c73ed, 0x2510a048, 0xa384d2e6 },   // WoR_HUD_light_0_pink, WoR_HUD_light_1_pink, WoR_HUD_light_2_pink
	{ 0x72eeaba9, 0x05e99b3f, 0x9ce0ca85 },   // WoR_HUD_light_0, WoR_HUD_light_1, WoR_HUD_light_2
	{ 0xb351c78a, 0x1526cc3e, 0x24ced6a3 },   // WoR_HUD_light_0_green, WoR_HUD_light_1_green, WoR_HUD_light_2_green
	{ 0x79e02c22, 0xb54a2cbc, 0x3bc52b5f },   // WoR_HUD_light_0_purple, WoR_HUD_light_1_purple, WoR_HUD_light_2_purple
	{ 0x5c19c88f, 0x97451b2a, 0x11d16984 },   // WoR_HUD_light_0_blue, WoR_HUD_light_1_blue, WoR_HUD_light_2_blue
};

static const uint32_t kOurLights[] = {
	0xee4c73ed, 0x2510a048, 0xa384d2e6,
	0x72eeaba9, 0x05e99b3f, 0x9ce0ca85,
	0xb351c78a, 0x1526cc3e, 0x24ced6a3,
	0x79e02c22, 0xb54a2cbc, 0x3bc52b5f,
	0x5c19c88f, 0x97451b2a, 0x11d16984,
};

// star power fill: stock name the DE sets -> our name (segments start on the second column)
static const uint32_t kSpFill[][2] = {
	{ 0x20273d7b, 0x4a17ef20 },   // hud_rock_tube_glow_full -> WoR_HUD_spseg
	{ 0x0a3c8de4, 0x3baed0b3 },   // hud_rock_tube_glow_full_b -> WoR_HUD_spseg_b
};
