// wor_hud_fixes.asi: native HUD fixes for the GH5 / Warriors of Rock HUD theme (GHWT: Definitive Edition, x86).
// Loaded by Ultimate ASI Loader (dinput8.dll). In-memory patches only; every patch site is byte-checked first and
// the plugin stays inert on any mismatch (another game build, or other code already patching the same place).
// Log: <game folder>\wor_hud_fixes.log. Reverse-engineering notes: docs/PLUGIN_NOTES.md.
//
// Fix 1, note-streak lights (senotestreaklights widget, set_lights 0x476590): for the WoR theme's widgets
//   - WoR's colours: x1 pink, x2 orange, x3 green, x4 purple, star power blue (the DE shares one set for x1/x2);
//   - our own texture names (WoR_HUD_light_*), which the stock z_in_game textures can't shadow from the 2nd song on.
// WoR widgets are recognised by their first light element's texture (the desc starts it on WoR_HUD_light_0, and
// the plugin only ever sets WoR_HUD_light_* names on it). Every other widget runs the game's own code.
//
// Fix 2, star power fill: the SP tube widget (update at 0x478630) sets the stock fill names on its segments with
// two SetTexture calls. For segments that still carry one of our fill names (the desc starts them on it) the
// stock name is replaced by ours, so the stock textures can't shadow ours from the 2nd song on.
//
// Fix 3, theme switch crash (DE bug): the font unload function (0x6403b0) searches the loaded-font table with a loop
// whose end bound the DE patches to its enlarged table while the start stays the original 0xeecd60, so unloading a
// font that isn't in the first 32 slots (the WoR numeral font, shipped in our theme pak) runs off into unmapped
// memory. On its first call the unload loop is given the same bounds as the DE-patched font-add loop (0x640720).
//
// Fix 3b, theme switch crash (2026-10-06): with the bounds fixed, the unload went through, and the game then crashed
// drawing (ReShade d3d9 under DrawPrimitiveUP) after our font was freed with the theme pak. A font is not copied out
// of its pak: the font object IS the pak's file data (byte-swapped and relocated in place by 0x6b78b0, linked into
// the font list 0xfc1090), so the font can't outlive the pak. Our numeral font is therefore made resident: when the
// game loads it (0x640930, cdecl: checksum, data, 0, size, ...) the plugin hands it a private copy of the file data
// that is never freed, and its unload (0x6403b0) is skipped. The next load of the theme finds it already registered
// (0x640930 returns the existing font first). Stock themes ship no fonts, so nothing else changes.
//
// Fix 4, smooth star power fill: after the SP tube update (0x478630) runs, WoR tubes get one continuous fill instead
// of six stretched segments: segments 1-5 are scaled to 0, segment 0 becomes the full-length glass-shaped fill
// (WoR_HUD_spfull, or _b with lightning when the game picked the charged texture, i.e. >= 50% or active) and its
// parent clip window's top edge is moved to the charge level (0-50% bottom -> half divider, 50-100% -> top).
//
// Fix 5, GH5's star power lifecycle (docs/GH5_STAR_POWER_REFERENCE.md): the clip window's per-frame update
// (element update 0x5a2dd0) drives the effect sprites: below 50% the charging fill + WoR's soft bottom glow; ready
// (>= 50% or active) the WoR Mat_Sp_Ready_Fire look as a 60 fps loop (WoR_HUD_spplasma_*) + the white-hot cap at
// the fill top; crossing into ready, a ball-lightning burst (16 frames at 20 fps) at the fill top.
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <tlhelp32.h>
#include <d3d9.h>
#pragma comment(lib, "user32.lib")
#include <cmath>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "names.h"   // generated by tools/gen_plugin_names.py: kLights[5][3], kOurLights[]

namespace
{
	// ---- GHWT_Definitive.exe addresses (image base 0x400000, PE timestamp 0x562b029a)
	constexpr uintptr_t kSetLights = 0x476590;       // void __thiscall set_lights(widget, int streak)
	constexpr uintptr_t kPlayerInfo = 0xc0c770;      // object for the multiplier query
	constexpr uintptr_t kStarPower = 0xc0d77c;       // object for the star power query
	constexpr uintptr_t kGetMultiplier = 0x42be60;   // int __thiscall (obj, player index, 1)    (DE thunk)
	constexpr uintptr_t kIsStarPower = 0x4649d0;     // bool __thiscall (obj, player index)      (DE thunk)
	constexpr uintptr_t kSetTexture = 0x59e6d0;      // void __thiscall (element, texture checksum)
	constexpr uintptr_t kHalf = 0xa0f028;            // double 0.5 (marks -> lights)
	constexpr uintptr_t kSpCall1 = 0x4786f5;         // call SetTexture(stock SP fill name) in the SP tube update
	constexpr uintptr_t kSpCall2 = 0x47877f;
	constexpr size_t kElementTexture = 0x214;        // sprite element: texture checksum
	constexpr uintptr_t kUnloadFont = 0x6403b0;      // cdecl (font checksum)
	constexpr uintptr_t kScoreFmtPush = 0x476505;    // push L"%d" (seinttostring widget update, 0x4764c0)
	constexpr uintptr_t kScoreFmtCall = 0x476511;    // call _snwprintf(buf, 10, L"%d", value) (0x4e5a80)
	constexpr uintptr_t kSnwprintf = 0x4e5a80;
	constexpr uintptr_t kParticleRead = 0x4aad13;    // Create2DParticleSystem (0x4aaae0): start/end scale just stored
	constexpr uintptr_t kLoadFont = 0x640930;        // cdecl (checksum, data, 0, size, flags, b, b) -> font
	constexpr uintptr_t kAddLoopStart = 0x64072f;    // imm32 of mov eax, <table start> in the font-add loop
	constexpr uintptr_t kAddLoopEnd = 0x640743;      // imm32 of cmp eax, <table end>
	constexpr uintptr_t kUnloadStarts[] = { 0x6403c9, 0x640417, 0x64041e };   // table start in the unload function
	constexpr uintptr_t kUnloadEnd = 0x6403dc;       // imm32 of cmp ecx, <table end>
	constexpr uint32_t kFontTable = 0xeecd60;        // original table (32 entries of 0x1c bytes)
	constexpr uint32_t kFontEntry = 0x1c;
	constexpr uintptr_t kTubeUpdate = 0x478630;      // void __thiscall (widget, value*, event*)
	constexpr uintptr_t kSetPos = 0x5a0fd0;          // void __thiscall (element, x, y, int)
	constexpr uintptr_t kSetScale = 0x5a17e0;        // void __thiscall (element, x, y, int, int)
	constexpr uintptr_t kSetDims = 0x5a1290;         // void __thiscall (element, w, h, int) (0x5a14e0 is SetJust)
	constexpr size_t kElementParent = 0x64;
	constexpr uint32_t kRefreshEvent = 0x8683400c;   // tube update event that only refreshes textures
	constexpr uintptr_t kElementUpdate = 0x5a2dd0;   // void __thiscall (element): per-frame update, recurses into children
	constexpr size_t kElementPos = 0xa8;             // float x, y (the position the desc gives, in the parent)
	constexpr size_t kElementScale = 0xc0;           // float x, y
	constexpr size_t kElementDims = 0x1bc;           // float w, h
	constexpr size_t kElementAlpha = 0x94;           // float alpha (tween target at +0x44 = 0xd8)
	constexpr size_t kElementFirstChild = 0x70;
	constexpr size_t kElementNextSibling = 0x7c;
	constexpr uintptr_t kTransformUpdate = 0x5a05e0; // void __thiscall (element): world alpha/scale/pos from the parent
	constexpr size_t kWorldScale = 0x18c;            // float x, y: parent world scale * own scale (0xc0)
	constexpr uintptr_t kCanvasScale = 0xd5ab7c;     // float x, y: 2D canvas -> screen (2.0, 1.5 at 2560x1080)
	constexpr uint32_t kFlagAlphaOnly = 0x80000;     // element flag: the update only recomputes alpha
	constexpr size_t kElementId = 0x2c;              // element id checksum (the constructor sets 0xdeadbeef)
	constexpr uint32_t kHudRoot = 0x39155705;        // hud_root
	constexpr uintptr_t kSetParent = 0x5a0240;       // void __thiscall (element, parent id): 0 = root; a missing parent crashes
	constexpr uintptr_t kElementManager = 0xd62eb8;  // [ ] -> the element manager the id lookups use
	constexpr uintptr_t kFindElement = 0x477c90;     // void *__thiscall (manager, id): 0 when no element has that id

	struct Site { uintptr_t addr; uint8_t bytes[16]; size_t len; const char *what; };
	const Site kSites[] = {
		{ kSetLights, { 0x53, 0x55, 0x56, 0x8B, 0xF1, 0x8B, 0x46, 0x0C, 0x8B, 0x0D, 0x70, 0xC7, 0xC0, 0x00 }, 14, "set_lights prologue" },
		{ 0x47659f, { 0x8B, 0x3D, 0x7C, 0xD7, 0xC0, 0x00 }, 6, "set_lights star power object" },
		{ 0x4765ae, { 0xE8 }, 1, "set_lights multiplier call" },
		{ kGetMultiplier, { 0xFF, 0x25, 0xC4, 0x21, 0xB6, 0x01 }, 6, "multiplier thunk" },
		{ kIsStarPower, { 0xFF, 0x25, 0xD8, 0x3C, 0xB6, 0x01 }, 6, "star power thunk" },
		{ kSetTexture, { 0x6A, 0xFF, 0x68, 0x83, 0xDA, 0x96, 0x00 }, 7, "SetTexture prologue" },
		{ 0x4766e0, { 0xE8 }, 1, "set_lights SetTexture call" },
		{ kSpCall1, { 0xE8 }, 1, "SP tube SetTexture call (1)" },
		{ kSpCall2, { 0xE8 }, 1, "SP tube SetTexture call (2)" },
		{ kUnloadFont, { 0x51, 0x57, 0x8B, 0x7C, 0x24, 0x0C, 0x6A, 0x00, 0x57, 0xE8 }, 10, "font unload prologue" },
		{ kLoadFont, { 0x57, 0x8B, 0x7C, 0x24, 0x08, 0x6A, 0x00, 0x57, 0xE8 }, 9, "font load prologue" },
		{ kParticleRead, { 0x8D, 0x56, 0x74, 0xB8, 0x9B, 0x05, 0x1B, 0x16 }, 8, "2D particle config (after scales)" },
		{ 0x4aad3c, { 0xB8, 0x2D, 0xC9, 0x43, 0xE2 }, 5, "2D particle config (emit params)" },
		{ kScoreFmtPush, { 0x68, 0x24, 0x0B, 0xA1, 0x00 }, 5, "score text format push" },
		{ kScoreFmtCall, { 0xE8 }, 1, "score text snwprintf call" },
		{ kAddLoopStart - 1, { 0xB8 }, 1, "font add loop start" },
		{ kAddLoopEnd - 1, { 0x3D }, 1, "font add loop end" },
		{ 0x6403c8, { 0xB9 }, 1, "font unload loop start" },
		{ 0x6403da, { 0x81, 0xF9 }, 2, "font unload loop end" },
		{ 0x640414, { 0x8B, 0x14, 0x8D }, 3, "font unload slot read" },
		{ 0x64041b, { 0x8D, 0x34, 0x8D }, 3, "font unload slot address" },
		{ kTubeUpdate, { 0x51, 0x53, 0x56, 0x8B, 0xF1, 0x80, 0x7E, 0x28, 0x00 }, 9, "SP tube update prologue" },
		{ 0x4786ff, { 0x8B, 0x4E, 0x1C }, 3, "SP tube segment vector" },
		{ kSetPos, { 0x56, 0x8B, 0xF1, 0xF3, 0x0F, 0x10, 0x86, 0xEC, 0x00, 0x00, 0x00 }, 11, "SetPos prologue" },
		{ kSetScale, { 0x56, 0x8B, 0xF1, 0xF3, 0x0F, 0x10, 0x86, 0x04, 0x01, 0x00, 0x00 }, 11, "SetScale prologue" },
		{ kSetDims, { 0x56, 0x8B, 0xF1, 0xF3, 0x0F, 0x10, 0x86, 0xBC, 0x01, 0x00, 0x00 }, 11, "SetDims prologue" },
		{ kElementUpdate, { 0x56, 0x8B, 0xF1, 0x8B, 0x46, 0x08, 0x83, 0x46, 0x54, 0x01 }, 10, "element update prologue" },
		{ 0x5a2e6e, { 0x8B, 0x7E, 0x70 }, 3, "element update first child" },
		{ 0x5a2e87, { 0x8B, 0x7F, 0x7C }, 3, "element update next sibling" },
		{ kTransformUpdate, { 0x83, 0xEC, 0x08, 0x56, 0x8B, 0xF1, 0x8B, 0x46, 0x64 }, 9, "element transform update prologue" },
		{ 0x5a06b6, { 0xF3, 0x0F, 0x11, 0x53, 0x2C }, 5, "transform update: world scale x store" },
		{ kSetParent, { 0x64, 0xA1, 0x00, 0x00, 0x00, 0x00, 0x6A, 0xFF, 0x68, 0x24, 0xDB, 0x96, 0x00 }, 13, "SetParent prologue" },
		{ 0x5a02ce, { 0x8B, 0x81, 0xD4, 0x01, 0x00, 0x00 }, 6, "SetParent parent read" },
		{ 0x517eec, { 0x8B, 0x0D, 0xB8, 0x2E, 0xD6, 0x00 }, 6, "element lookup manager" },
		{ kFindElement, { 0x53, 0x56, 0x8B, 0xD9, 0x8B, 0x73, 0x08 }, 7, "element lookup by id" },
	};

	// thiscall functions called through fastcall pointers (ecx = this, edx unused, callee cleans the stack)
	using GetMultiplierFn = int(__fastcall *)(void *self, void *edx, int player, int one);
	using IsStarPowerFn = bool(__fastcall *)(void *self, void *edx, int player);
	using SetTextureFn = void(__fastcall *)(void *element, void *edx, uint32_t texture);
	using SetLightsFn = void(__fastcall *)(void *widget, void *edx, int streak);

	SetLightsFn g_original = nullptr;
	FILE *g_log = nullptr;

	void log(const char *fmt, ...)
	{
		if (!g_log)
			return;
		va_list ap;
		va_start(ap, fmt);
		vfprintf(g_log, fmt, ap);
		va_end(ap);
		fputc('\n', g_log);
		fflush(g_log);
	}

	bool is_ours(uint32_t texture)
	{
		for (uint32_t t : kOurLights)
			if (t == texture)
				return true;
		return false;
	}

	uint32_t texture_of(void *element)
	{
		return *reinterpret_cast<uint32_t *>(static_cast<uint8_t *>(element) + kElementTexture);
	}

	bool is_our_fill(uint32_t texture)
	{
		for (const auto &p : kSpFill)
			if (p[1] == texture)
				return true;
		return false;
	}

	bool is_plasma(uint32_t t)
	{
		for (uint32_t p : kPlasma)
			if (p == t)
				return true;
		return false;
	}

	// replaces the two SP tube SetTexture calls: same calling convention (thiscall, one stack argument)
	void __fastcall sp_set_texture_hook(void *element, void *edx, uint32_t texture)
	{
		const uint32_t current = element ? texture_of(element) : 0;
		if (element && (is_our_fill(current) || current == kSpFull || current == kSpFullB || is_plasma(current)))
		{
			for (const auto &p : kSpFill)
			{
				if (p[0] == texture)
				{
					texture = p[1];
					break;
				}
			}
		}
		reinterpret_cast<SetTextureFn>(kSetTexture)(element, edx, texture);
	}

	uint8_t *field(void *base, size_t off) { return static_cast<uint8_t *>(base) + off; }

	void __fastcall set_lights_hook(void *widget, void *edx, int streak)
	{
		void **elements = reinterpret_cast<void **>(field(widget, 0x1c));
		if (elements[0] == nullptr || !is_ours(*reinterpret_cast<uint32_t *>(field(elements[0], kElementTexture))))
		{
			g_original(widget, edx, streak);
			return;
		}
		const int player = *reinterpret_cast<int *>(field(widget, 0xc)) - 1;
		const int mult = reinterpret_cast<GetMultiplierFn>(kGetMultiplier)(*reinterpret_cast<void **>(kPlayerInfo), nullptr, player, 1);
		const bool sp = reinterpret_cast<IsStarPowerFn>(kIsStarPower)(*reinterpret_cast<void **>(kStarPower), nullptr, player);
		const int set = sp ? 4 : mult >= 4 ? 3 : mult == 3 ? 2 : mult == 2 ? 1 : 0;   // pink, orange, green, purple, blue

		// same mark maths as the game: 10 marks over 5 lights, 2 marks per light
		int s = streak < 0 ? 0 : streak > 30 ? 30 : streak;
		int marks = s % 10;
		if (s > 0 && marks == 0)
			marks = 10;
		const int full = static_cast<int>(marks * *reinterpret_cast<const double *>(kHalf));
		const int half = full + (marks & 1);
		const auto set_texture = reinterpret_cast<SetTextureFn>(kSetTexture);
		for (int k = 0; k < 5; ++k)
			set_texture(elements[k], nullptr, kLights[set][k < full ? 2 : k < half ? 1 : 0]);
	}

	bool sites_match()
	{
		for (const Site &s : kSites)
		{
			if (memcmp(reinterpret_cast<const void *>(s.addr), s.bytes, s.len) != 0)
			{
				log("inert: %s at 0x%08x does not match this game build", s.what, static_cast<unsigned>(s.addr));
				return false;
			}
		}
		if (*reinterpret_cast<const double *>(kHalf) != 0.5)
		{
			log("inert: constant at 0x%08x is not 0.5", static_cast<unsigned>(kHalf));
			return false;
		}
		return true;
	}

	bool install_set_lights()
	{
		// trampoline: the first 5 bytes (push ebx; push ebp; push esi; mov esi, ecx) + jmp back
		uint8_t *tramp = static_cast<uint8_t *>(VirtualAlloc(nullptr, 16, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE));
		if (!tramp)
			return false;
		memcpy(tramp, reinterpret_cast<const void *>(kSetLights), 5);
		tramp[5] = 0xE9;
		*reinterpret_cast<int32_t *>(tramp + 6) = static_cast<int32_t>((kSetLights + 5) - reinterpret_cast<uintptr_t>(tramp + 10));
		g_original = reinterpret_cast<SetLightsFn>(tramp);

		DWORD old = 0;
		if (!VirtualProtect(reinterpret_cast<void *>(kSetLights), 5, PAGE_EXECUTE_READWRITE, &old))
			return false;
		uint8_t *p = reinterpret_cast<uint8_t *>(kSetLights);
		p[0] = 0xE9;
		*reinterpret_cast<int32_t *>(p + 1) = static_cast<int32_t>(reinterpret_cast<uintptr_t>(&set_lights_hook) - (kSetLights + 5));
		VirtualProtect(p, 5, old, &old);
		FlushInstructionCache(GetCurrentProcess(), p, 5);
		return true;
	}

	uint32_t read32(uintptr_t a) { return *reinterpret_cast<const uint32_t *>(a); }

	void write32(uintptr_t a, uint32_t v)
	{
		DWORD old = 0;
		VirtualProtect(reinterpret_cast<void *>(a), 4, PAGE_EXECUTE_READWRITE, &old);
		*reinterpret_cast<uint32_t *>(a) = v;
		VirtualProtect(reinterpret_cast<void *>(a), 4, old, &old);
		FlushInstructionCache(GetCurrentProcess(), reinterpret_cast<void *>(a), 4);
	}

	bool readable(uint32_t a, uint32_t n)
	{
		MEMORY_BASIC_INFORMATION mi{};
		for (uint32_t p = a; p < a + n; p = static_cast<uint32_t>(reinterpret_cast<uintptr_t>(mi.BaseAddress) + mi.RegionSize))
		{
			if (!VirtualQuery(reinterpret_cast<void *>(static_cast<uintptr_t>(p)), &mi, sizeof(mi)) || mi.State != MEM_COMMIT ||
			    (mi.Protect & (PAGE_NOACCESS | PAGE_GUARD)))
				return false;
		}
		return true;
	}

	// Gives the unload loop the add loop's bounds (read now: the DE patches them after the plugin loads).
	void fix_font_bounds()
	{
		const uint32_t s = read32(kAddLoopStart), e = read32(kAddLoopEnd);
		const uint32_t us = read32(kUnloadStarts[0]), ue = read32(kUnloadEnd);
		log("font table: add loop %08x..%08x, unload loop %08x..%08x", s, e, us, ue);
		if (us == s && ue == e)
		{
			log("font table: consistent, nothing to do");
			return;
		}
		if (e <= s || (e - s) % kFontEntry != 0 || !readable(s, e - s))
		{
			log("font table: add loop bounds look wrong, left alone");
			return;
		}
		for (uintptr_t a : kUnloadStarts)
			if (read32(a) == kFontTable || read32(a) == us)
				write32(a, s);
		write32(kUnloadEnd, e);
		log("font table: unload loop now %08x..%08x (%u slots)", read32(kUnloadStarts[0]), read32(kUnloadEnd), (e - s) / kFontEntry);
	}

	using UnloadFontFn = uint32_t(__cdecl *)(uint32_t font);
	UnloadFontFn g_unload_font = nullptr;
	bool g_font_fixed = false;

	using LoadFontFn = void *(__cdecl *)(uint32_t font, void *data, uint32_t zero, uint32_t size, uint32_t flags,
	                                     uint32_t b1, uint32_t b2);
	LoadFontFn g_load_font = nullptr;
	void *g_font_copy = nullptr;     // our font's file data, private and never freed (the font object lives in it)

	void *__cdecl load_font_hook(uint32_t font, void *data, uint32_t zero, uint32_t size, uint32_t flags, uint32_t b1,
	                             uint32_t b2)
	{
		if (font == kScoreFont && !g_font_copy && data && size > 0x20000 && size < 0x1000000 && readable(
		        reinterpret_cast<uintptr_t>(data), size))
		{
			void *copy = VirtualAlloc(nullptr, size, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
			if (copy)
			{
				memcpy(copy, data, size);
				void *f = g_load_font(font, copy, zero, size, flags, b1, b2);
				if (f)
					g_font_copy = copy;
				else
					VirtualFree(copy, 0, MEM_RELEASE);
				log("score font: %s (%u bytes, font %p)", f ? "loaded from a resident copy" : "copy load failed", size, f);
				if (f)
					return f;
			}
		}
		else if (font == kScoreFont && !g_font_copy)
			log("score font: unexpected load arguments (data %p, size %u), left to the game", data, size);
		return g_load_font(font, data, zero, size, flags, b1, b2);
	}

	uint32_t __cdecl unload_font_hook(uint32_t font)
	{
		if (!g_font_fixed)
		{
			g_font_fixed = true;
			fix_font_bounds();
		}
		if (font == kScoreFont && g_font_copy)
		{
			log("score font: unload skipped (resident)");
			return 0;
		}
		return g_unload_font(font);
	}

	// ---- star power: smooth fill and GH5's lifecycle effects
	using TubeUpdateFn = void(__fastcall *)(void *widget, void *edx, void *value, void *event);
	using ElementUpdateFn = void(__fastcall *)(void *element, void *edx);
	using SetPosFn = void(__fastcall *)(void *element, void *edx, float x, float y, int flag);
	using SetScaleFn = void(__fastcall *)(void *element, void *edx, float x, float y, int a, int b);
	using SetDimsFn = void(__fastcall *)(void *element, void *edx, float w, float h, int flag);
	TubeUpdateFn g_tube_update = nullptr;
	ElementUpdateFn g_element_update = nullptr;
	bool g_tube_logged = false;

	bool is_tube_texture(uint32_t t)
	{
		return is_our_fill(t) || t == kSpFull || t == kSpFullB || is_plasma(t);
	}

	float &f32(void *e, size_t off) { return *reinterpret_cast<float *>(field(e, off)); }

	// alpha: current 0x94, tween target 0xd8 (element tween 0x5a21d0); 0x400 = recompute on the next update
	void set_alpha(void *e, float a)
	{
		if (f32(e, kElementAlpha) == a && f32(e, kElementAlpha + 0x44) == a)
			return;
		f32(e, kElementAlpha) = a;
		f32(e, kElementAlpha + 0x44) = a;
		*reinterpret_cast<uint32_t *>(field(e, 8)) |= 0x400;
	}

	void set_texture(void *e, uint32_t t)
	{
		if (texture_of(e) != t)
			reinterpret_cast<SetTextureFn>(kSetTexture)(e, nullptr, t);
	}

	struct StarPower
	{
		void *clip = nullptr, *fill = nullptr, *parent = nullptr;
		void *glow[3] = {};    // bottom glow, cap (white), cap (colour)
		void *burst[3] = {};
		void *star_bar = nullptr, *star_lead = nullptr, *prog_fill = nullptr, *prog_lead = nullptr, *star_fire = nullptr;
		void *feather[kFeathers] = {};   // soft fill top: clip windows above the level, each with a faded fill copy
		int feathers = 0;
		bool effects = false;  // effect sprites found and the alpha field checked
		float level = 0.0f;    // displayed level (glides between the DE's updates)
		float target = 0.0f;   // the DE's latest level
		float from = 0.0f;     // glide start
		double glide_t0 = 0.0, glide_dur = 0.0, last_update = 0.0;
		bool ready = false, seen = false;
		double burst_t0 = -1.0;
	} g_sp;
	LARGE_INTEGER g_qpf = {};

	double now()
	{
		LARGE_INTEGER c;
		QueryPerformanceCounter(&c);
		return static_cast<double>(c.QuadPart) / static_cast<double>(g_qpf.QuadPart);
	}

	void level_point(float level, float &x, float &y)
	{
		const float f = level * kLevelSteps;
		int i = static_cast<int>(f);
		i = i < 0 ? 0 : i >= kLevelSteps ? kLevelSteps - 1 : i;
		const float t = f - i;
		x = kLevelPt[i][0] + (kLevelPt[i + 1][0] - kLevelPt[i][0]) * t;
		y = kLevelPt[i][1] + (kLevelPt[i + 1][1] - kLevelPt[i][1]) * t;
	}

	// a new clip window (new song / HUD): find the effect sprites among its siblings by their texture names
	void discover(void *clip, void *fill)
	{
		g_sp = StarPower();
		g_sp.clip = clip;
		g_sp.fill = fill;
		g_sp.parent = *reinterpret_cast<void **>(field(clip, kElementParent));
		if (!g_sp.parent)
			return;
		int bursts = 0;
		for (void *e = *reinterpret_cast<void **>(field(g_sp.parent, kElementFirstChild)); e;
		     e = *reinterpret_cast<void **>(field(e, kElementNextSibling)))
		{
			const uint32_t t = texture_of(e);
			for (int k = 0; k < 3; ++k)
				if (t == kGlowTex[k])
					g_sp.glow[k] = e;
			if (t == kBall[0] && bursts < 3)
				g_sp.burst[bursts++] = e;
			if (t == kStarBar)
				g_sp.star_bar = e;
			else if (t == kStarLead)
				g_sp.star_lead = e;
			else if (t == kProgFill)
				g_sp.prog_fill = e;
			else if (t == kProgLead)
				g_sp.prog_lead = e;
			else if (t == kStarFire[0])
				g_sp.star_fire = e;
			void *child = *reinterpret_cast<void **>(field(e, kElementFirstChild));
			if (e != clip && child && texture_of(child) == kSpFull && g_sp.feathers < kFeathers)
				g_sp.feather[g_sp.feathers++] = e;
		}
		bool ok = bursts == 3;
		for (void *g : g_sp.glow)
			ok = ok && g && f32(g, kElementAlpha) == 0.0f;       // the desc starts them hidden
		ok = ok && f32(g_sp.parent, kElementAlpha) == 1.0f;       // and their container visible
		g_sp.effects = ok;
		log("star power effects: %s (glows %p %p %p, bursts %d, feathers %d)", ok ? "found" : "not found, fill only",
		    g_sp.glow[0], g_sp.glow[1], g_sp.glow[2], bursts, g_sp.feathers);
		log("score box effects: star bar %p lead %p, song line %p lead %p, star fire %p", g_sp.star_bar, g_sp.star_lead,
		    g_sp.prog_fill, g_sp.prog_lead, g_sp.star_fire);
	}

	float level_y(float level)
	{
		if (level <= 0.5f)
			return kLevel0 + (kLevel50 - kLevel0) * (level / 0.5f);
		return kLevel50 + (kLevel100 - kLevel50) * ((level - 0.5f) / 0.5f);
	}

	// the feather windows: bands of kFeatherH / kFeathers above the level, each showing the fill's texture faded (the
	// desc gives each band's fill its alpha), so the fill's top edge is a soft gradient instead of a pixel-hard cut
	void place_feathers()
	{
		const auto set_pos = reinterpret_cast<SetPosFn>(kSetPos);
		const auto set_dims = reinterpret_cast<SetDimsFn>(kSetDims);
		const bool hidden = g_sp.level <= 0.001f || g_sp.level >= 0.999f;
		const float top = hidden ? 0.0f : level_y(g_sp.level), band = kFeatherH / kFeathers;
		for (int k = 0; k < g_sp.feathers; ++k)
		{
			void *win = g_sp.feather[k];
			void *fill = *reinterpret_cast<void **>(field(win, kElementFirstChild));
			const float hi = top - (k + 1) * band, lo = top;   // nested: every window ends at the level
			const float t = hi < kClipY ? kClipY : hi;
			if (hidden || !fill || lo - t <= 0.0f)
			{
				set_dims(win, nullptr, kClipW, 0.0f, 0);
				continue;
			}
			set_texture(fill, texture_of(g_sp.fill));
			set_dims(win, nullptr, kClipW, lo - t, 0);
			set_pos(win, nullptr, kClipX, t, 1);
			set_pos(fill, nullptr, kFillX - kClipX, kFillY - t, 1);
		}
	}

	// the clip window's top edge is the displayed level (none at 0, unclipped at 100%); it keeps its bottom
	void place_fill()
	{
		const auto set_pos = reinterpret_cast<SetPosFn>(kSetPos);
		const auto set_dims = reinterpret_cast<SetDimsFn>(kSetDims);
		const float level = g_sp.level, bottom = kClipY + kClipH;
		const float top = level >= 0.999f ? kClipY : level <= 0.001f ? bottom : level_y(level);
		set_dims(g_sp.clip, nullptr, kClipW, bottom - top, 0);
		set_pos(g_sp.clip, nullptr, kClipX, top, 1);
		set_pos(g_sp.fill, nullptr, kFillX - kClipX, kFillY - top, 1);
	}

	// the star bar's and the song line's dots (WoR's HUD_star_lead): comets with the dot at kCometHead of their width,
	// placed on the tip of the bar the DE grows (scale / dims set by its own scripts); the star's fire glow loop + swell
	void place_score_effects(double t)
	{
		const auto set_pos = reinterpret_cast<SetPosFn>(kSetPos);
		if (g_sp.star_bar && g_sp.star_lead)
		{
			const float w = f32(g_sp.star_bar, kElementDims) * f32(g_sp.star_bar, kElementScale);
			const float x = f32(g_sp.star_bar, kElementPos) + w - (kCometHead - 0.5f) * 64.0f * kStarLeadS;
			set_pos(g_sp.star_lead, nullptr, x, f32(g_sp.star_bar, kElementPos + 4), 1);
			set_alpha(g_sp.star_lead, w > 2.0f ? 1.0f : 0.0f);
		}
		if (g_sp.prog_fill && g_sp.prog_lead)
		{
			const float w = f32(g_sp.prog_fill, kElementDims);
			const float x = f32(g_sp.prog_fill, kElementPos) + w - (kCometHead - 0.5f) * 64.0f * kProgLeadS;
			set_pos(g_sp.prog_lead, nullptr, x, f32(g_sp.prog_fill, kElementPos + 4) + f32(g_sp.prog_fill, kElementDims + 4) * 0.5f, 1);
			set_alpha(g_sp.prog_lead, w > 2.0f ? 1.0f : 0.0f);
		}
		if (g_sp.star_fire)
		{
			set_texture(g_sp.star_fire, kStarFire[static_cast<long long>(t * kFireFps) % (sizeof(kStarFire) / sizeof(kStarFire[0]))]);
			set_alpha(g_sp.star_fire, kFireBase + kFireAmp * static_cast<float>(sin(t * 6.2831853 * kFireHz)));
		}
	}

	// every frame (from the clip window's own update, game thread)
	void sp_frame()
	{
		if (*reinterpret_cast<void **>(field(g_sp.clip, kElementFirstChild)) != g_sp.fill ||
		    !is_tube_texture(texture_of(g_sp.fill)))
		{
			g_sp = StarPower();   // not our window any more
			return;
		}
		const double t = now();
		if (g_sp.glide_dur > 0.0)
		{
			const double u = (t - g_sp.glide_t0) / g_sp.glide_dur;
			g_sp.level = u >= 1.0 ? g_sp.target : g_sp.from + (g_sp.target - g_sp.from) * static_cast<float>(u);
			if (u >= 1.0)
				g_sp.glide_dur = 0.0;
		}
		place_fill();
		place_score_effects(t);
		const bool shown = g_sp.level > 0.001f;
		if (g_sp.ready && shown)
			set_texture(g_sp.fill, kPlasma[static_cast<long long>(t * kPlasmaFps) % (sizeof(kPlasma) / sizeof(kPlasma[0]))]);
		place_feathers();
		if (!g_sp.effects)
			return;
		const auto set_pos = reinterpret_cast<SetPosFn>(kSetPos);
		float x, y;
		level_point(g_sp.level, x, y);
		set_alpha(g_sp.glow[0], shown ? kGlowAlpha[0] : 0.0f);
		for (int k = 1; k < 3; ++k)
		{
			if (g_sp.ready && shown)
				set_pos(g_sp.glow[k], nullptr, x, y, 1);
			set_alpha(g_sp.glow[k], g_sp.ready && shown ? kGlowAlpha[k] : 0.0f);
		}
		if (g_sp.burst_t0 >= 0.0)
		{
			const double dt = t - g_sp.burst_t0;
			const bool on = dt < kBurstEnd;
			const float fade = dt <= kBurstHold ? 1.0f : static_cast<float>(1.0 - (dt - kBurstHold) / (kBurstEnd - kBurstHold));
			for (int k = 0; k < 3; ++k)
			{
				if (on)
				{
					set_texture(g_sp.burst[k], kBall[(static_cast<int>(dt * kBallFps) + k * 5) % 16]);
					set_pos(g_sp.burst[k], nullptr, x + kBurstOff[k][0], y + kBurstOff[k][1], 1);
				}
				set_alpha(g_sp.burst[k], on ? fade : 0.0f);
			}
			if (!on)
				g_sp.burst_t0 = -1.0;
		}
	}

	// ---- Fix 12, career rock needle (1.22): the DE's script 0x97e11003 ("no side meter in this game mode") is true in
	// p1_career, so single-player career never attached the health widget to our sliding needle. A mod can't redefine a
	// DE script, so the mod ships the same logic as WoR_HUD_career_side_meter (p1_career is a normal mode while the HUD
	// theme has the WoR_HUD_career_meter flag) and, once the mod's QB is loaded, 0x97e11003's symbol entry takes that
	// script's type and data. QB symbol table: [kSymbolTable] -> buckets[checksum & 0x7fff], entry +2 type (7 = script),
	// +4 checksum, +0xc value, +0x10 next (lookups in RunScript 0x4f1c20 and 0x4446bb).
	constexpr uintptr_t kSymbolTable = 0xd48f5c;
	bool g_script_swaps_done = false;

	// Script swaps, done once the mod's QB is loaded: `target` (a DE script) takes the type and data of `with` (a mod
	// script); when `save_to` is set, the DE script's own data first moves there, so the mod's wrapper can still call it.
	struct ScriptSwap { uint32_t target, with, save_to; const char *what; };
	const ScriptSwap kScriptSwaps[] = {
		// Fix 12 (1.22): rock needle in single-player career
		{ 0x97e11003, 0x82d6743f /* wor_hud_career_side_meter */, 0,
		  "career rock needle: 0x97e11003 now runs WoR_HUD_career_side_meter (side meter in p1_career with the WoR theme)" },
		// Fix 13 (1.23): WoR's highway star power effect (DE port 0x68e7427a, never spawned by the DE), started and
		// faded out by wrappers around the star power on / off sound scripts, which still run afterwards
		{ 0xdf84b375 /* GH_Star_Power_Verb_On */, 0xd4b7e2cc /* wor_hud_sp_verb_on */, 0x9c4c4383 /* _orig */,
		  "star power highway: GH_Star_Power_Verb_On wrapped (WoR highway effect on)" },
		{ 0x4cb84f65 /* GH_Star_Power_Verb_Off */, 0xfe0e771c /* wor_hud_sp_verb_off */, 0x3ac324fb /* _orig */,
		  "star power highway: GH_Star_Power_Verb_Off wrapped (WoR highway effect off)" },
	};

	uint8_t *find_symbol(uint32_t checksum)
	{
		uint8_t **buckets = *reinterpret_cast<uint8_t ***>(kSymbolTable);
		if (!buckets)
			return nullptr;
		for (uint8_t *e = buckets[checksum & 0x7fff]; e; e = *reinterpret_cast<uint8_t **>(e + 0x10))
			if (*reinterpret_cast<uint32_t *>(e + 4) == checksum)
				return e;
		return nullptr;
	}

	// a symbol's type and value: flags + type (+0..3), +8 and the script data (+0xc); +4 checksum, +0x10 next stay
	void copy_symbol(uint8_t *dst, const uint8_t *src)
	{
		memcpy(dst, src, 4);
		memcpy(dst + 8, src + 8, 8);
	}

	void script_swaps_try()
	{
		if (!find_symbol(kScriptSwaps[0].with))
			return;                                       // the mod's QB isn't loaded yet
		g_script_swaps_done = true;
		for (const ScriptSwap &s : kScriptSwaps)
		{
			uint8_t *dst = find_symbol(s.target), *src = find_symbol(s.with), *save = s.save_to ? find_symbol(s.save_to) : nullptr;
			if (!dst || !src || (s.save_to && !save) || dst[2] != 7 || src[2] != 7 || (save && save[2] != 7))
			{
				log("script swap %08x <- %08x skipped (missing or unexpected symbols)", s.target, s.with);
				continue;
			}
			if (save)
				copy_symbol(save, dst);
			copy_symbol(dst, src);
			log("%s", s.what);
		}
	}

	void __fastcall element_update_hook(void *element, void *edx)
	{
		if (element && element == g_sp.clip)
			sp_frame();
		if (!g_script_swaps_done)
			script_swaps_try();
		g_element_update(element, edx);
	}

	// ---- Fix 14, missing parents (1.24): SetParent reads the parent it looked up without a null check, so a
	// CreateScreenElement whose parent id doesn't exist crashes the game (star power with 1.23). Such an element goes to
	// the root, hidden, and the ids are logged.
	using SetParentFn = void(__fastcall *)(void *element, void *edx, uint32_t parent);
	using FindElementFn = void *(__fastcall *)(void *manager, void *edx, uint32_t id);
	SetParentFn g_set_parent = nullptr;
	int g_missing_parents = 0;

	void __fastcall set_parent_hook(void *element, void *edx, uint32_t parent)
	{
		void *manager = *reinterpret_cast<void **>(kElementManager);
		if (parent && manager && !reinterpret_cast<FindElementFn>(kFindElement)(manager, nullptr, parent))
		{
			if (g_missing_parents++ < 64)
				log("missing parent: element %08x asked for parent %08x (attached to the root, hidden)",
				    *reinterpret_cast<uint32_t *>(field(element, kElementId)), parent);
			g_set_parent(element, edx, 0);
			*reinterpret_cast<float *>(field(element, kElementAlpha)) = 0.0f;
			*reinterpret_cast<float *>(field(element, kElementAlpha + 0x44)) = 0.0f;
			return;
		}
		g_set_parent(element, edx, parent);
	}

	void __fastcall tube_update_hook(void *widget, void *edx, void *value, void *event)
	{
		g_tube_update(widget, edx, value, event);
		void **first = *reinterpret_cast<void ***>(field(widget, 0x1c));
		void **last = *reinterpret_cast<void ***>(field(widget, 0x20));
		if (!first || last - first < 6 || !first[0] || !is_tube_texture(texture_of(first[0])))
			return;
		void *fill = first[0];
		void *clip = *reinterpret_cast<void **>(field(fill, kElementParent));
		if (!clip)
			return;
		const float lo = *reinterpret_cast<float *>(field(widget, 0xc)), hi = *reinterpret_cast<float *>(field(widget, 0x10));
		if (*reinterpret_cast<uint32_t *>(field(event, 4)) == kRefreshEvent || hi <= lo)
			return;   // texture refresh only: the last level stays
		if (clip != g_sp.clip || fill != g_sp.fill)
			discover(clip, fill);
		float level = (**reinterpret_cast<float **>(value) - lo) / (hi - lo);
		level = level < 0.0f ? 0.0f : level > 1.0f ? 1.0f : level;
		const bool charged = texture_of(fill) == kSpFill[1][1];    // the game picked the _b texture (>= 50% or active)
		// GH5's ready burst: the meter crosses into ready (not on the first update of a HUD, not on activation)
		if (g_sp.seen && charged && !g_sp.ready && level >= 0.49f && g_sp.effects)
			g_sp.burst_t0 = now();
		// GH5 jumps on phrase gains; small changes (whammy, drain: the DE updates ~10 times a second) glide over the
		// time since the previous update, so the bar moves every frame
		const double t = now();
		if (!g_sp.seen || (level > g_sp.level ? level - g_sp.level : g_sp.level - level) > kSnap)
		{
			g_sp.level = g_sp.from = level;
			g_sp.glide_dur = 0.0;
		}
		else
		{
			const double gap = t - g_sp.last_update;
			g_sp.from = g_sp.level;
			g_sp.glide_t0 = t;
			g_sp.glide_dur = gap < 1.0 / 60.0 ? 1.0 / 60.0 : gap > 0.25 ? 0.25 : gap;
		}
		g_sp.target = level;
		g_sp.last_update = t;
		g_sp.seen = true;
		g_sp.ready = charged;

		const auto set_scale = reinterpret_cast<SetScaleFn>(kSetScale);
		const auto set_dims = reinterpret_cast<SetDimsFn>(kSetDims);
		reinterpret_cast<SetTextureFn>(kSetTexture)(fill, nullptr, charged ? kSpFullB : kSpFull);   // plasma next frame
		for (void **p = first + 1; p < first + 6; ++p)
			if (*p)
				set_scale(*p, nullptr, 0.0f, 0.0f, 0, 0);
		// SetPos only moves the element now with a non-zero flag (0 = tween target)
		set_scale(fill, nullptr, kFillSX, kFillSY, 0, 0);
		set_dims(fill, nullptr, 64.0f, 256.0f, 0);
		sp_frame();   // window, texture, cap and glow right away
		if (!g_tube_logged)
		{
			g_tube_logged = true;
			log("star power fill: smooth fill active (level %.2f, %s)", level, charged ? "charged" : "charging");
		}
	}

	// 5-byte jmp at site to target; the first `len` bytes (whole instructions) move to a trampoline
	void *install_jmp(uintptr_t site, size_t len, void *target)
	{
		uint8_t *tramp = static_cast<uint8_t *>(VirtualAlloc(nullptr, 32, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE));
		if (!tramp)
			return nullptr;
		memcpy(tramp, reinterpret_cast<const void *>(site), len);
		tramp[len] = 0xE9;
		*reinterpret_cast<int32_t *>(tramp + len + 1) = static_cast<int32_t>((site + len) - reinterpret_cast<uintptr_t>(tramp + len + 5));
		DWORD old = 0;
		if (!VirtualProtect(reinterpret_cast<void *>(site), len, PAGE_EXECUTE_READWRITE, &old))
			return nullptr;
		uint8_t *p = reinterpret_cast<uint8_t *>(site);
		p[0] = 0xE9;
		*reinterpret_cast<int32_t *>(p + 1) = static_cast<int32_t>(reinterpret_cast<uintptr_t>(target) - (site + 5));
		for (size_t i = 5; i < len; ++i)
			p[i] = 0x90;
		VirtualProtect(p, len, old, &old);
		FlushInstructionCache(GetCurrentProcess(), p, len);
		return tramp;
	}

	bool install_call(uintptr_t site, void *target)
	{
		DWORD old = 0;
		if (!VirtualProtect(reinterpret_cast<void *>(site), 5, PAGE_EXECUTE_READWRITE, &old))
			return false;
		uint8_t *p = reinterpret_cast<uint8_t *>(site);
		*reinterpret_cast<int32_t *>(p + 1) = static_cast<int32_t>(reinterpret_cast<uintptr_t>(target) - (site + 5));
		VirtualProtect(p, 5, old, &old);
		FlushInstructionCache(GetCurrentProcess(), p, 5);
		return true;
	}

	// the score widget formats its number with _snwprintf(buf, 10, L"%d", value); with the WoR HUD up the number gets
	// thousands separators (WoR: "84,225"). Falls back to the game's own call when it would not fit the 10 wchar buffer.
	int __cdecl score_text_hook(wchar_t *buf, size_t count, const wchar_t *fmt, int value)
	{
		const auto orig = reinterpret_cast<int(__cdecl *)(wchar_t *, size_t, const wchar_t *, int)>(kSnwprintf);
		if (!g_sp.star_bar || value < 0 || count < 2)
			return orig(buf, count, fmt, value);
		wchar_t digits[12];
		int n = 0;
		for (unsigned v = static_cast<unsigned>(value); n < 11; v /= 10)
		{
			digits[n++] = static_cast<wchar_t>(L'0' + v % 10);
			if (v < 10)
				break;
		}
		const int len = n + (n - 1) / 3;
		if (static_cast<size_t>(len) + 1 > count)
			return orig(buf, count, fmt, value);
		int o = 0;
		for (int i = n - 1; i >= 0; --i)
		{
			buf[o++] = digits[i];
			if (i > 0 && i % 3 == 0)
				buf[o++] = L',';
		}
		buf[o] = 0;
		return o;
	}

	// Create2DParticleSystem config slot (esi): +0x10/+0x14 start_scale, +0x20/+0x24 end_scale, +0x44 material,
	// +0x5c start_color (r, g, b, a bytes). With the WoR HUD up, the star power phrase burst (GuitarEvent_StarSequenceBonus)
	// gets WoR's particle sizes: Star01 0.55 -> 0.25, Star02 0.5 -> 0.125 at half alpha, its cyan Spark01 1.5 -> 0.5
	// (only that one: the gem explosions use Spark01 at other sizes). A mod cannot redefine the script itself.
	void *g_particle_tramp = nullptr;

	void __cdecl particle_fix(uint8_t *cfg)
	{
		if (!g_sp.star_bar || !cfg)
			return;
		float *ss = reinterpret_cast<float *>(cfg + 0x10), *es = reinterpret_cast<float *>(cfg + 0x20);
		const uint32_t mat = *reinterpret_cast<uint32_t *>(cfg + 0x44);
		if (mat == 0xab62af58 && ss[0] > 0.54f && ss[0] < 0.56f)            // sys_Particle_Star01
			ss[0] = ss[1] = 0.25f;
		else if (mat == 0x49757c01 && ss[0] > 0.49f && ss[0] < 0.51f)       // sys_Particle_Star02
		{
			ss[0] = ss[1] = 0.125f;
			es[0] = es[1] = 0.15f;
			cfg[0x5f] = static_cast<uint8_t>(cfg[0x5f] / 2);
		}
		else if (mat == 0xc5c51fee && ss[0] > 1.49f && ss[0] < 1.51f)       // sys_Particle_Spark01 (burst only)
			ss[0] = ss[1] = 0.5f;
	}

	__declspec(naked) void particle_hook()
	{
		__asm {
			pushad
			pushfd
			push esi
			call particle_fix
			add esp, 4
			popfd
			popad
			jmp dword ptr [g_particle_tramp]
		}
	}

	// ---- ultrawide probe (diagnostic, log only). 1.14: write breakpoints found the canvas scale (0xd5ab7c/80) written
	// from outside the exe. 1.17: READ/write breakpoints on the canvas scale x/y and the screen width float (0xd5ab60)
	// log every distinct instruction that touches them (module + offset, caller), for ~1 min, then disarm: the readers
	// are the 2D renderer's canvas -> screen mapping, where the HUD/menus get drawn as a centred 16:9 picture.
	constexpr uintptr_t kProbe[] = { 0xd5ab7c, 0xd5ab80, 0xd5ab60 };
	constexpr int kProbeMaxSites = 48;
	uintptr_t g_probe_sites[kProbeMaxSites] = {};
	volatile LONG g_probe_count = 0;
	volatile LONG g_probe_armed = 1;

	void probe_where(uintptr_t a, char *out, size_t n)
	{
		HMODULE m = nullptr;
		char name[MAX_PATH] = "?";
		if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
		                       reinterpret_cast<LPCSTR>(a), &m) && m)
		{
			GetModuleFileNameA(m, name, MAX_PATH);
			const char *b = strrchr(name, '\\');
			_snprintf_s(out, n, _TRUNCATE, "%s+0x%x", b ? b + 1 : name, static_cast<unsigned>(a - reinterpret_cast<uintptr_t>(m)));
		}
		else
			_snprintf_s(out, n, _TRUNCATE, "0x%08x", static_cast<unsigned>(a));
	}

	LONG CALLBACK probe_veh(EXCEPTION_POINTERS *ep)
	{
		if (ep->ExceptionRecord->ExceptionCode != EXCEPTION_SINGLE_STEP)
			return EXCEPTION_CONTINUE_SEARCH;
		CONTEXT *c = ep->ContextRecord;
		const DWORD hit = c->Dr6 & 0xf;
		if (!hit)
			return EXCEPTION_CONTINUE_SEARCH;
		c->Dr6 = 0;
		if (!g_probe_armed)
		{
			c->Dr7 = 0;                    // late hit after disarming: switch this thread's breakpoints off
			return EXCEPTION_CONTINUE_EXECUTION;
		}
		const uintptr_t eip = c->Eip;
		const LONG n = g_probe_count;
		for (LONG i = 0; i < n && i < kProbeMaxSites; ++i)
			if (g_probe_sites[i] == eip)
				return EXCEPTION_CONTINUE_EXECUTION;
		const LONG slot = InterlockedIncrement(&g_probe_count) - 1;
		if (slot >= kProbeMaxSites)
			return EXCEPTION_CONTINUE_EXECUTION;
		g_probe_sites[slot] = eip;
		char where[MAX_PATH + 32], caller[MAX_PATH + 32];
		probe_where(eip, where, sizeof where);
		const uintptr_t ret = !IsBadReadPtr(reinterpret_cast<void *>(c->Esp), 4) ? *reinterpret_cast<const uintptr_t *>(c->Esp) : 0;
		probe_where(ret, caller, sizeof caller);
		for (int k = 0; k < 3; ++k)
			if (hit & (1u << k))
				log("ultrawide probe: access 0x%08x (now %.3f) by eip %s (after the access), [esp] %s, thread %u",
				    static_cast<unsigned>(kProbe[k]), *reinterpret_cast<const float *>(kProbe[k]), where, caller,
				    static_cast<unsigned>(GetCurrentThreadId()));
		return EXCEPTION_CONTINUE_EXECUTION;
	}

	void probe_arm_threads(bool on)
	{
		const DWORD pid = GetCurrentProcessId(), me = GetCurrentThreadId();
		HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
		THREADENTRY32 te = { sizeof te };
		int armed = 0;
		for (BOOL ok = Thread32First(snap, &te); ok; ok = Thread32Next(snap, &te))
		{
			if (te.th32OwnerProcessID != pid || te.th32ThreadID == me)
				continue;
			HANDLE t = OpenThread(THREAD_GET_CONTEXT | THREAD_SET_CONTEXT | THREAD_SUSPEND_RESUME, FALSE, te.th32ThreadID);
			if (!t)
				continue;
			SuspendThread(t);
			CONTEXT c = {};
			c.ContextFlags = CONTEXT_DEBUG_REGISTERS;
			if (GetThreadContext(t, &c))
			{
				c.Dr0 = kProbe[0]; c.Dr1 = kProbe[1]; c.Dr2 = kProbe[2];
				c.Dr7 = on ? ((1 << 0) | (1 << 2) | (1 << 4)       // local enable DR0-2
				           | (0x3 << 16) | (0x3 << 18)             // DR0: read/write, 4 bytes
				           | (0x3 << 20) | (0x3 << 22)             // DR1
				           | (0x3 << 24) | (0x3 << 26)) : 0;       // DR2
				if (SetThreadContext(t, &c))
					++armed;
			}
			ResumeThread(t);
			CloseHandle(t);
		}
		CloseHandle(snap);
		log(on ? "ultrawide probe: read/write breakpoints armed on %d threads" : "ultrawide probe: disarmed on %d threads", armed);
	}

	DWORD WINAPI probe_thread(void *)
	{
		AddVectoredExceptionHandler(1, probe_veh);
		for (int round = 0; round < 14; ++round)        // ~70 s: boot, menus, a song
		{
			probe_arm_threads(true);                      // re-arm: threads created later (render thread) are covered
			Sleep(5000);
		}
		g_probe_armed = 0;
		probe_arm_threads(false);
		log("ultrawide probe: %d distinct sites", static_cast<int>(g_probe_count));
		return 0;
	}

	// ---- Fix 9, ultrawide (2026-10-09): the 2D canvas (1280x720) is scaled to the window with separate x / y factors
	// (0xd5ab7c / 0xd5ab80; 2.0 / 1.5 at 2560x1080), so every sprite and text is stretched sideways. Positions are right
	// (the user wants the layout as it is); only the drawn width is wrong. After the engine's transform update
	// (0x5a05e0), a LEAF element (no children: sprites, text) gets its world x scale multiplied by sy / sx, so it keeps
	// its position (computed from the parent's world scale, untouched) and draws at the canvas's true aspect. Containers
	// keep their scale, so children stay where they are. No effect at 16:9 (factor 1).
	using TransformUpdateFn = void(__fastcall *)(void *element, void *edx);
	TransformUpdateFn g_transform_update = nullptr;
	volatile LONG g_unstretch_logged = 0;

	void __fastcall transform_update_hook(void *e, void *edx)
	{
		g_transform_update(e, edx);
		const float sx = *reinterpret_cast<const float *>(kCanvasScale), sy = *reinterpret_cast<const float *>(kCanvasScale + 4);
		if (!(sx > 0.0f) || !(sy > 0.0f) || sy >= sx * 0.999f)
			return;                                            // 16:9 or narrower: nothing stretched sideways
		void *parent = *reinterpret_cast<void **>(field(e, kElementParent));
		if (!parent || *reinterpret_cast<void **>(field(e, kElementFirstChild)))
			return;                                            // root or container
		if (*reinterpret_cast<uint32_t *>(field(e, 8)) & kFlagAlphaOnly)
			return;                                            // the engine didn't recompute the scale this time
		// HUD only: the highway and gems are 2D sprites too, and narrowing them while the lanes keep their positions
		// would put the gems off the highway. Act only under hud_root (element id at +0x2c).
		bool in_hud = false;
		void *p = parent;
		for (int depth = 0; p && depth < 32; ++depth, p = *reinterpret_cast<void **>(field(p, kElementParent)))
			if (*reinterpret_cast<uint32_t *>(field(p, kElementId)) == kHudRoot)
			{
				in_hud = true;
				break;
			}
		if (!in_hud)
			return;
		const float own = *reinterpret_cast<float *>(field(e, kElementScale));
		const float pw = *reinterpret_cast<float *>(field(parent, kWorldScale));
		*reinterpret_cast<float *>(field(e, kWorldScale)) = pw * own * (sy / sx);
		if (InterlockedExchange(&g_unstretch_logged, 1) == 0)
			log("ultrawide: un-stretching 2D elements, width factor %.4f (canvas scale %.3f x %.3f)", sy / sx, sx, sy);
	}

	// ---- Fix 10, ultrawide (1.18): the 2D layer (HUD, menus) is drawn as the closest 16:9 picture, centred. The screen
	// struct at 0xd5ab60 holds the canvas -> screen mapping: scale x/y (+0x1c/+0x20) and pixel offsets x/y (+0x24/+0x28;
	// the exe's own letterbox at 0x668cc0 changes +0x20 and +0x28). It is copied around by memcpy, so it is kept at the
	// 16:9 values: scale x = scale y, offset x = (width - 16/9 * height) / 2. 3D is not affected.
	DWORD WINAPI canvas_thread(void *)
	{
		float *sc = reinterpret_cast<float *>(0xd5ab7c);
		int *off = reinterpret_cast<int *>(0xd5ab84);
		bool logged = false;
		for (;;)
		{
			const float w = *reinterpret_cast<const float *>(0xd5ab60), h = *reinterpret_cast<const float *>(0xd5ab64);
			if (w > 0.0f && h > 0.0f && w / h > 16.0f / 9.0f + 0.01f && sc[1] > 0.0f)
			{
				const float k = sc[1];                                   // the y scale (1.5 at 1080 lines)
				const int ox = static_cast<int>((w - 1280.0f * k) * 0.5f + 0.5f);
				if (sc[0] != k || off[0] != ox)
				{
					sc[0] = k;
					off[0] = ox;
					if (!logged)
						log("ultrawide: 2D canvas drawn at 16:9, scale %.3f, x offset %d px (screen %.0f x %.0f)", k, ox, w, h);
					logged = true;
				}
			}
			Sleep(50);
		}
	}

	// ---- Fix 11, ultrawide (1.20): all 2D (HUD, menus, text, the 2D highway) is drawn with pre-transformed screen-space
	// vertices (FVF XYZRHW / decl POSITIONT) through DrawPrimitiveUP / DrawIndexedPrimitiveUP. On a screen wider than
	// 16:9 those vertices are remapped x' = off + x * k (k = 16/9 * h / w, off = (w - 16/9 * h) / 2): the 2D becomes a
	// centred 16:9 picture, unstretched; 3D (transformed vertices) is untouched. Hooked in the system d3d9's device
	// vtable (shared by every device, ReShade forwards to it).
	using DrawUPFn = HRESULT(STDMETHODCALLTYPE *)(IDirect3DDevice9 *, D3DPRIMITIVETYPE, UINT, const void *, UINT);
	using DrawIdxUPFn = HRESULT(STDMETHODCALLTYPE *)(IDirect3DDevice9 *, D3DPRIMITIVETYPE, UINT, UINT, UINT, const void *, D3DFORMAT, const void *, UINT);
	DrawUPFn g_draw_up = nullptr;
	DrawIdxUPFn g_draw_idx_up = nullptr;
	volatile LONG g_remapped = 0;

	UINT prim_vertices(D3DPRIMITIVETYPE t, UINT n)
	{
		switch (t)
		{
		case D3DPT_POINTLIST: return n;
		case D3DPT_LINELIST: return n * 2;
		case D3DPT_LINESTRIP: return n + 1;
		case D3DPT_TRIANGLELIST: return n * 3;
		case D3DPT_TRIANGLESTRIP: case D3DPT_TRIANGLEFAN: return n + 2;
		default: return 0;
		}
	}

	// byte offset of the screen-space position in the current vertex format, or -1 if the draw isn't pre-transformed
	int rhw_offset(IDirect3DDevice9 *dev)
	{
		DWORD fvf = 0;
		if (SUCCEEDED(dev->GetFVF(&fvf)) && fvf)
			return (fvf & D3DFVF_POSITION_MASK) == D3DFVF_XYZRHW ? 0 : -1;
		IDirect3DVertexDeclaration9 *decl = nullptr;
		if (FAILED(dev->GetVertexDeclaration(&decl)) || !decl)
			return -1;
		D3DVERTEXELEMENT9 el[MAXD3DDECLLENGTH + 1];
		UINT n = MAXD3DDECLLENGTH + 1;
		int off = -1;
		if (SUCCEEDED(decl->GetDeclaration(el, &n)))
			for (UINT i = 0; i < n && el[i].Stream != 0xff; ++i)
				if (el[i].Stream == 0 && el[i].Usage == D3DDECLUSAGE_POSITIONT && el[i].Type == D3DDECLTYPE_FLOAT4)
					off = el[i].Offset;
		decl->Release();
		return off;
	}

	// remapped copy of the vertices, or nullptr to draw unchanged
	const void *remap(IDirect3DDevice9 *dev, const void *data, UINT count, UINT stride)
	{
		static thread_local uint8_t *buf = nullptr;
		static thread_local size_t cap = 0;
		if (!data || !count || stride < 16)
			return nullptr;
		D3DVIEWPORT9 vp;
		if (FAILED(dev->GetViewport(&vp)) || vp.Height == 0 || vp.Width * 9 <= vp.Height * 16 + 9)
			return nullptr;                                  // 16:9 or narrower
		const int off = rhw_offset(dev);
		if (off < 0)
			return nullptr;
		const float w169 = vp.Height * 16.0f / 9.0f, k = w169 / vp.Width, ox = vp.X + (vp.Width - w169) * 0.5f;
		const size_t bytes = static_cast<size_t>(count) * stride;
		if (bytes > cap)
		{
			delete[] buf;
			cap = bytes * 2;
			buf = new uint8_t[cap];
		}
		memcpy(buf, data, bytes);
		for (UINT i = 0; i < count; ++i)
		{
			float *x = reinterpret_cast<float *>(buf + static_cast<size_t>(i) * stride + off);
			*x = ox + (*x - vp.X) * k;
		}
		if (InterlockedIncrement(&g_remapped) == 1)
			log("ultrawide: remapping 2D draws to 16:9 (k %.4f, offset %.1f px, viewport %lu x %lu)", k, ox, vp.Width, vp.Height);
		return buf;
	}

	HRESULT STDMETHODCALLTYPE draw_up_hook(IDirect3DDevice9 *dev, D3DPRIMITIVETYPE t, UINT n, const void *data, UINT stride)
	{
		const void *r = remap(dev, data, prim_vertices(t, n), stride);
		return g_draw_up(dev, t, n, r ? r : data, stride);
	}

	HRESULT STDMETHODCALLTYPE draw_idx_up_hook(IDirect3DDevice9 *dev, D3DPRIMITIVETYPE t, UINT minv, UINT nv, UINT n,
	                                           const void *idx, D3DFORMAT fmt, const void *data, UINT stride)
	{
		const void *r = remap(dev, data, minv + nv, stride);
		return g_draw_idx_up(dev, t, minv, nv, n, idx, fmt, r ? r : data, stride);
	}

	DWORD WINAPI d3d_hook_thread(void *)
	{
		char path[MAX_PATH];
		GetSystemDirectoryA(path, MAX_PATH);
		strcat_s(path, "\\d3d9.dll");                     // the system one (ReShade's d3d9.dll forwards to it)
		HMODULE d3d = LoadLibraryA(path);
		auto create = d3d ? reinterpret_cast<IDirect3D9 *(WINAPI *)(UINT)>(GetProcAddress(d3d, "Direct3DCreate9")) : nullptr;
		IDirect3D9 *d = create ? create(D3D_SDK_VERSION) : nullptr;
		if (!d)
		{
			log("ultrawide: no system d3d9");
			return 0;
		}
		HWND wnd = CreateWindowExA(0, "STATIC", "wor_hud_fixes", WS_POPUP, 0, 0, 16, 16, nullptr, nullptr, nullptr, nullptr);
		D3DPRESENT_PARAMETERS pp = {};
		pp.Windowed = TRUE;
		pp.SwapEffect = D3DSWAPEFFECT_DISCARD;
		pp.hDeviceWindow = wnd;
		pp.BackBufferFormat = D3DFMT_UNKNOWN;
		IDirect3DDevice9 *dev = nullptr;
		HRESULT hr = d->CreateDevice(D3DADAPTER_DEFAULT, D3DDEVTYPE_NULLREF, wnd, D3DCREATE_SOFTWARE_VERTEXPROCESSING, &pp, &dev);
		if (FAILED(hr) || !dev)
			hr = d->CreateDevice(D3DADAPTER_DEFAULT, D3DDEVTYPE_HAL, wnd, D3DCREATE_SOFTWARE_VERTEXPROCESSING, &pp, &dev);
		if (FAILED(hr) || !dev)
		{
			log("ultrawide: dummy device failed (0x%08lx)", hr);
			d->Release();
			DestroyWindow(wnd);
			return 0;
		}
		void **vt = *reinterpret_cast<void ***>(dev);
		DWORD old = 0;
		if (VirtualProtect(&vt[83], 2 * sizeof(void *), PAGE_EXECUTE_READWRITE, &old))
		{
			g_draw_up = reinterpret_cast<DrawUPFn>(vt[83]);
			g_draw_idx_up = reinterpret_cast<DrawIdxUPFn>(vt[84]);
			vt[83] = reinterpret_cast<void *>(&draw_up_hook);
			vt[84] = reinterpret_cast<void *>(&draw_idx_up_hook);
			VirtualProtect(&vt[83], 2 * sizeof(void *), old, &old);
			log("ultrawide: DrawPrimitiveUP / DrawIndexedPrimitiveUP hooked in the d3d9 device vtable");
		}
		dev->Release();          // the vtable lives in d3d9.dll, which stays loaded
		d->Release();
		DestroyWindow(wnd);
		return 0;
	}

	void init(HMODULE self)
	{
		char path[MAX_PATH] = {};
		GetModuleFileNameA(nullptr, path, MAX_PATH);
		if (char *slash = strrchr(path, '\\'))
			strcpy_s(slash + 1, MAX_PATH - (slash + 1 - path), "wor_hud_fixes.log");
		fopen_s(&g_log, path, "w");
		log("wor_hud_fixes 1.24 (GH5 / WoR HUD)");
		if (!sites_match())
			return;
		log(install_set_lights() ? "streak lights: patched (WoR colours, x1 pink, own texture names)"
		                         : "streak lights: patch failed (VirtualProtect)");
		const bool sp = install_call(kSpCall1, reinterpret_cast<void *>(&sp_set_texture_hook)) &&
		                install_call(kSpCall2, reinterpret_cast<void *>(&sp_set_texture_hook));
		log(sp ? "star power fill: patched (own texture names)" : "star power fill: patch failed (VirtualProtect)");
		// push ecx; push edi; mov edi, [esp+0xc] = 6 bytes of whole instructions
		g_unload_font = reinterpret_cast<UnloadFontFn>(install_jmp(kUnloadFont, 6, reinterpret_cast<void *>(&unload_font_hook)));
		g_load_font = reinterpret_cast<LoadFontFn>(install_jmp(kLoadFont, 5, reinterpret_cast<void *>(&load_font_hook)));
		log(g_load_font ? "score font: load hooked (kept resident)" : "score font: load hook failed");
		log(g_unload_font ? "font unload: hooked (bounds fixed on first use)" : "font unload: hook failed");
		// push ecx; push ebx; push esi; mov esi, ecx = 5 bytes of whole instructions
		g_tube_update = reinterpret_cast<TubeUpdateFn>(install_jmp(kTubeUpdate, 5, reinterpret_cast<void *>(&tube_update_hook)));
		log(g_tube_update ? "star power fill: smooth fill hooked" : "star power fill: smooth fill hook failed");
		// push esi; mov esi, ecx; mov eax, [esi+8] = 6 bytes of whole instructions
		QueryPerformanceFrequency(&g_qpf);
		g_element_update = reinterpret_cast<ElementUpdateFn>(install_jmp(kElementUpdate, 6, reinterpret_cast<void *>(&element_update_hook)));
		log(g_element_update ? "star power effects: per-frame hook installed" : "star power effects: per-frame hook failed");
		// mov eax, fs:[0] = 6 bytes, one whole instruction
		g_set_parent = reinterpret_cast<SetParentFn>(install_jmp(kSetParent, 6, reinterpret_cast<void *>(&set_parent_hook)));
		log(g_set_parent ? "missing parents: SetParent guarded" : "missing parents: SetParent hook failed");
		g_particle_tramp = install_jmp(kParticleRead, 8, reinterpret_cast<void *>(&particle_hook));
		// sub esp, 8; push esi; mov esi, ecx = 6 bytes of whole instructions
#ifdef WOR_LEAF_UNSTRETCH   // 1.16 experiment: skewed rotated sprites and misaligned layers; replaced by the 16:9 plan
		g_transform_update = reinterpret_cast<TransformUpdateFn>(install_jmp(kTransformUpdate, 6, reinterpret_cast<void *>(&transform_update_hook)));
		log(g_transform_update ? "ultrawide: transform update hooked (2D elements keep their aspect)" : "ultrawide: hook failed");
#endif
		log(g_particle_tramp ? "star power burst: particle sizes hooked (WoR sizes)" : "star power burst: hook failed");
		{
			const uint8_t *call = reinterpret_cast<const uint8_t *>(kScoreFmtCall);
			const uintptr_t target = kScoreFmtCall + 5 + *reinterpret_cast<const int32_t *>(call + 1);
			const bool ok = target == kSnwprintf && install_call(kScoreFmtCall, reinterpret_cast<void *>(&score_text_hook));
			log(ok ? "score text: thousands separators hooked" : "score text: hook failed (unexpected call target)");
		}
#ifdef WOR_ULTRAWIDE_PROBE   // 1.17 read probe (results in MODLOG); off in normal builds
		if (HANDLE t = CreateThread(nullptr, 0, probe_thread, nullptr, 0, nullptr))
			CloseHandle(t);
#endif
#ifdef WOR_CANVAS_STRUCT   // 1.18 experiment: values written, no effect on screen (renderer uses copies); menus slowed
		if (HANDLE t = CreateThread(nullptr, 0, canvas_thread, nullptr, 0, nullptr))
			CloseHandle(t);
#endif
#ifdef WOR_D3D_UP_REMAP   // 1.20 experiment: never fired (the 2D is not pre-transformed); ultrawide is the standalone add-on
		if (HANDLE t = CreateThread(nullptr, 0, d3d_hook_thread, nullptr, 0, nullptr))
			CloseHandle(t);
#endif
		(void)self;
	}
}

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID)
{
	if (reason == DLL_PROCESS_ATTACH)
	{
		DisableThreadLibraryCalls(module);
		init(module);
	}
	return TRUE;
}
