// wor_hud_fixes.asi: native HUD fixes for the GH5 / Warriors of Rock HUD theme (GHWT: Definitive Edition, x86).
// Loaded by Ultimate ASI Loader (dinput8.dll). In-memory patches only; every patch site is byte-checked first and
// the plugin stays inert on any mismatch (another game build, or other code already patching the same place).
// Log: <game folder>\wor_hud_fixes.log. Reverse-engineering notes: docs/PLUGIN_NOTES.md.
//
// Fix 1, note-streak lights (senotestreaklights widget, set_lights 0x476590): for the WoR theme's widgets
//   - WoR's colours: x1 pink, x2 orange, x3 green, x4 purple, star power blue (the DE shares one set for x1/x2);
//   - our own texture names (WoR_HUD_light_*), which the stock z_in_game textures can't shadow from the 2nd song on.
// WoR widgets are recognised by their first light element's texture (the desc starts it on WoR_HUD_light_0, and
// the plugin only ever sets WoR_HUD_light_* names on it). Every other widget runs the game's own code.
//
// Fix 2, star power fill: the SP tube widget (update at 0x478630) sets the stock fill names on its segments with
// two SetTexture calls. For segments that still carry one of our fill names (the desc starts them on it) the
// stock name is replaced by ours, so the stock textures can't shadow ours from the 2nd song on.
//
// Fix 3, theme switch crash (DE bug): the font unload function (0x6403b0) searches the loaded-font table with a loop
// whose end bound the DE patches to its enlarged table while the start stays the original 0xeecd60, so unloading a
// font that isn't in the first 32 slots (the WoR numeral font, shipped in our theme pak) runs off into unmapped
// memory. On its first call the unload loop is given the same bounds as the DE-patched font-add loop (0x640720).
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "names.h"   // generated by tools/gen_plugin_names.py: kLights[5][3], kOurLights[]

namespace
{
	// ---- GHWT_Definitive.exe addresses (image base 0x400000, PE timestamp 0x562b029a)
	constexpr uintptr_t kSetLights = 0x476590;       // void __thiscall set_lights(widget, int streak)
	constexpr uintptr_t kPlayerInfo = 0xc0c770;      // object for the multiplier query
	constexpr uintptr_t kStarPower = 0xc0d77c;       // object for the star power query
	constexpr uintptr_t kGetMultiplier = 0x42be60;   // int __thiscall (obj, player index, 1)    (DE thunk)
	constexpr uintptr_t kIsStarPower = 0x4649d0;     // bool __thiscall (obj, player index)      (DE thunk)
	constexpr uintptr_t kSetTexture = 0x59e6d0;      // void __thiscall (element, texture checksum)
	constexpr uintptr_t kHalf = 0xa0f028;            // double 0.5 (marks -> lights)
	constexpr uintptr_t kSpCall1 = 0x4786f5;         // call SetTexture(stock SP fill name) in the SP tube update
	constexpr uintptr_t kSpCall2 = 0x47877f;
	constexpr size_t kElementTexture = 0x214;        // sprite element: texture checksum
	constexpr uintptr_t kUnloadFont = 0x6403b0;      // cdecl (font checksum)
	constexpr uintptr_t kAddLoopStart = 0x64072f;    // imm32 of mov eax, <table start> in the font-add loop
	constexpr uintptr_t kAddLoopEnd = 0x640743;      // imm32 of cmp eax, <table end>
	constexpr uintptr_t kUnloadStarts[] = { 0x6403c9, 0x640417, 0x64041e };   // table start in the unload function
	constexpr uintptr_t kUnloadEnd = 0x6403dc;       // imm32 of cmp ecx, <table end>
	constexpr uint32_t kFontTable = 0xeecd60;        // original table (32 entries of 0x1c bytes)
	constexpr uint32_t kFontEntry = 0x1c;

	struct Site { uintptr_t addr; uint8_t bytes[16]; size_t len; const char *what; };
	const Site kSites[] = {
		{ kSetLights, { 0x53, 0x55, 0x56, 0x8B, 0xF1, 0x8B, 0x46, 0x0C, 0x8B, 0x0D, 0x70, 0xC7, 0xC0, 0x00 }, 14, "set_lights prologue" },
		{ 0x47659f, { 0x8B, 0x3D, 0x7C, 0xD7, 0xC0, 0x00 }, 6, "set_lights star power object" },
		{ 0x4765ae, { 0xE8 }, 1, "set_lights multiplier call" },
		{ kGetMultiplier, { 0xFF, 0x25, 0xC4, 0x21, 0xB6, 0x01 }, 6, "multiplier thunk" },
		{ kIsStarPower, { 0xFF, 0x25, 0xD8, 0x3C, 0xB6, 0x01 }, 6, "star power thunk" },
		{ kSetTexture, { 0x6A, 0xFF, 0x68, 0x83, 0xDA, 0x96, 0x00 }, 7, "SetTexture prologue" },
		{ 0x4766e0, { 0xE8 }, 1, "set_lights SetTexture call" },
		{ kSpCall1, { 0xE8 }, 1, "SP tube SetTexture call (1)" },
		{ kSpCall2, { 0xE8 }, 1, "SP tube SetTexture call (2)" },
		{ kUnloadFont, { 0x51, 0x57, 0x8B, 0x7C, 0x24, 0x0C, 0x6A, 0x00, 0x57, 0xE8 }, 10, "font unload prologue" },
		{ kAddLoopStart - 1, { 0xB8 }, 1, "font add loop start" },
		{ kAddLoopEnd - 1, { 0x3D }, 1, "font add loop end" },
		{ 0x6403c8, { 0xB9 }, 1, "font unload loop start" },
		{ 0x6403da, { 0x81, 0xF9 }, 2, "font unload loop end" },
		{ 0x640414, { 0x8B, 0x14, 0x8D }, 3, "font unload slot read" },
		{ 0x64041b, { 0x8D, 0x34, 0x8D }, 3, "font unload slot address" },
	};

	// thiscall functions called through fastcall pointers (ecx = this, edx unused, callee cleans the stack)
	using GetMultiplierFn = int(__fastcall *)(void *self, void *edx, int player, int one);
	using IsStarPowerFn = bool(__fastcall *)(void *self, void *edx, int player);
	using SetTextureFn = void(__fastcall *)(void *element, void *edx, uint32_t texture);
	using SetLightsFn = void(__fastcall *)(void *widget, void *edx, int streak);

	SetLightsFn g_original = nullptr;
	FILE *g_log = nullptr;

	void log(const char *fmt, ...)
	{
		if (!g_log)
			return;
		va_list ap;
		va_start(ap, fmt);
		vfprintf(g_log, fmt, ap);
		va_end(ap);
		fputc('\n', g_log);
		fflush(g_log);
	}

	bool is_ours(uint32_t texture)
	{
		for (uint32_t t : kOurLights)
			if (t == texture)
				return true;
		return false;
	}

	uint32_t texture_of(void *element)
	{
		return *reinterpret_cast<uint32_t *>(static_cast<uint8_t *>(element) + kElementTexture);
	}

	bool is_our_fill(uint32_t texture)
	{
		for (const auto &p : kSpFill)
			if (p[1] == texture)
				return true;
		return false;
	}

	// replaces the two SP tube SetTexture calls: same calling convention (thiscall, one stack argument)
	void __fastcall sp_set_texture_hook(void *element, void *edx, uint32_t texture)
	{
		if (element && is_our_fill(texture_of(element)))
		{
			for (const auto &p : kSpFill)
			{
				if (p[0] == texture)
				{
					texture = p[1];
					break;
				}
			}
		}
		reinterpret_cast<SetTextureFn>(kSetTexture)(element, edx, texture);
	}

	uint8_t *field(void *base, size_t off) { return static_cast<uint8_t *>(base) + off; }

	void __fastcall set_lights_hook(void *widget, void *edx, int streak)
	{
		void **elements = reinterpret_cast<void **>(field(widget, 0x1c));
		if (elements[0] == nullptr || !is_ours(*reinterpret_cast<uint32_t *>(field(elements[0], kElementTexture))))
		{
			g_original(widget, edx, streak);
			return;
		}
		const int player = *reinterpret_cast<int *>(field(widget, 0xc)) - 1;
		const int mult = reinterpret_cast<GetMultiplierFn>(kGetMultiplier)(*reinterpret_cast<void **>(kPlayerInfo), nullptr, player, 1);
		const bool sp = reinterpret_cast<IsStarPowerFn>(kIsStarPower)(*reinterpret_cast<void **>(kStarPower), nullptr, player);
		const int set = sp ? 4 : mult >= 4 ? 3 : mult == 3 ? 2 : mult == 2 ? 1 : 0;   // pink, orange, green, purple, blue

		// same mark maths as the game: 10 marks over 5 lights, 2 marks per light
		int s = streak < 0 ? 0 : streak > 30 ? 30 : streak;
		int marks = s % 10;
		if (s > 0 && marks == 0)
			marks = 10;
		const int full = static_cast<int>(marks * *reinterpret_cast<const double *>(kHalf));
		const int half = full + (marks & 1);
		const auto set_texture = reinterpret_cast<SetTextureFn>(kSetTexture);
		for (int k = 0; k < 5; ++k)
			set_texture(elements[k], nullptr, kLights[set][k < full ? 2 : k < half ? 1 : 0]);
	}

	bool sites_match()
	{
		for (const Site &s : kSites)
		{
			if (memcmp(reinterpret_cast<const void *>(s.addr), s.bytes, s.len) != 0)
			{
				log("inert: %s at 0x%08x does not match this game build", s.what, static_cast<unsigned>(s.addr));
				return false;
			}
		}
		if (*reinterpret_cast<const double *>(kHalf) != 0.5)
		{
			log("inert: constant at 0x%08x is not 0.5", static_cast<unsigned>(kHalf));
			return false;
		}
		return true;
	}

	bool install_set_lights()
	{
		// trampoline: the first 5 bytes (push ebx; push ebp; push esi; mov esi, ecx) + jmp back
		uint8_t *tramp = static_cast<uint8_t *>(VirtualAlloc(nullptr, 16, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE));
		if (!tramp)
			return false;
		memcpy(tramp, reinterpret_cast<const void *>(kSetLights), 5);
		tramp[5] = 0xE9;
		*reinterpret_cast<int32_t *>(tramp + 6) = static_cast<int32_t>((kSetLights + 5) - reinterpret_cast<uintptr_t>(tramp + 10));
		g_original = reinterpret_cast<SetLightsFn>(tramp);

		DWORD old = 0;
		if (!VirtualProtect(reinterpret_cast<void *>(kSetLights), 5, PAGE_EXECUTE_READWRITE, &old))
			return false;
		uint8_t *p = reinterpret_cast<uint8_t *>(kSetLights);
		p[0] = 0xE9;
		*reinterpret_cast<int32_t *>(p + 1) = static_cast<int32_t>(reinterpret_cast<uintptr_t>(&set_lights_hook) - (kSetLights + 5));
		VirtualProtect(p, 5, old, &old);
		FlushInstructionCache(GetCurrentProcess(), p, 5);
		return true;
	}

	uint32_t read32(uintptr_t a) { return *reinterpret_cast<const uint32_t *>(a); }

	void write32(uintptr_t a, uint32_t v)
	{
		DWORD old = 0;
		VirtualProtect(reinterpret_cast<void *>(a), 4, PAGE_EXECUTE_READWRITE, &old);
		*reinterpret_cast<uint32_t *>(a) = v;
		VirtualProtect(reinterpret_cast<void *>(a), 4, old, &old);
		FlushInstructionCache(GetCurrentProcess(), reinterpret_cast<void *>(a), 4);
	}

	bool readable(uint32_t a, uint32_t n)
	{
		MEMORY_BASIC_INFORMATION mi{};
		for (uint32_t p = a; p < a + n; p = static_cast<uint32_t>(reinterpret_cast<uintptr_t>(mi.BaseAddress) + mi.RegionSize))
		{
			if (!VirtualQuery(reinterpret_cast<void *>(static_cast<uintptr_t>(p)), &mi, sizeof(mi)) || mi.State != MEM_COMMIT ||
			    (mi.Protect & (PAGE_NOACCESS | PAGE_GUARD)))
				return false;
		}
		return true;
	}

	// Gives the unload loop the add loop's bounds (read now: the DE patches them after the plugin loads).
	void fix_font_bounds()
	{
		const uint32_t s = read32(kAddLoopStart), e = read32(kAddLoopEnd);
		const uint32_t us = read32(kUnloadStarts[0]), ue = read32(kUnloadEnd);
		log("font table: add loop %08x..%08x, unload loop %08x..%08x", s, e, us, ue);
		if (us == s && ue == e)
		{
			log("font table: consistent, nothing to do");
			return;
		}
		if (e <= s || (e - s) % kFontEntry != 0 || !readable(s, e - s))
		{
			log("font table: add loop bounds look wrong, left alone");
			return;
		}
		for (uintptr_t a : kUnloadStarts)
			if (read32(a) == kFontTable || read32(a) == us)
				write32(a, s);
		write32(kUnloadEnd, e);
		log("font table: unload loop now %08x..%08x (%u slots)", read32(kUnloadStarts[0]), read32(kUnloadEnd), (e - s) / kFontEntry);
	}

	using UnloadFontFn = uint32_t(__cdecl *)(uint32_t font);
	UnloadFontFn g_unload_font = nullptr;
	bool g_font_fixed = false;

	uint32_t __cdecl unload_font_hook(uint32_t font)
	{
		if (!g_font_fixed)
		{
			g_font_fixed = true;
			fix_font_bounds();
		}
		return g_unload_font(font);
	}

	// 5-byte jmp at site to target; the first `len` bytes (whole instructions) move to a trampoline
	void *install_jmp(uintptr_t site, size_t len, void *target)
	{
		uint8_t *tramp = static_cast<uint8_t *>(VirtualAlloc(nullptr, 32, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE));
		if (!tramp)
			return nullptr;
		memcpy(tramp, reinterpret_cast<const void *>(site), len);
		tramp[len] = 0xE9;
		*reinterpret_cast<int32_t *>(tramp + len + 1) = static_cast<int32_t>((site + len) - reinterpret_cast<uintptr_t>(tramp + len + 5));
		DWORD old = 0;
		if (!VirtualProtect(reinterpret_cast<void *>(site), len, PAGE_EXECUTE_READWRITE, &old))
			return nullptr;
		uint8_t *p = reinterpret_cast<uint8_t *>(site);
		p[0] = 0xE9;
		*reinterpret_cast<int32_t *>(p + 1) = static_cast<int32_t>(reinterpret_cast<uintptr_t>(target) - (site + 5));
		for (size_t i = 5; i < len; ++i)
			p[i] = 0x90;
		VirtualProtect(p, len, old, &old);
		FlushInstructionCache(GetCurrentProcess(), p, len);
		return tramp;
	}

	bool install_call(uintptr_t site, void *target)
	{
		DWORD old = 0;
		if (!VirtualProtect(reinterpret_cast<void *>(site), 5, PAGE_EXECUTE_READWRITE, &old))
			return false;
		uint8_t *p = reinterpret_cast<uint8_t *>(site);
		*reinterpret_cast<int32_t *>(p + 1) = static_cast<int32_t>(reinterpret_cast<uintptr_t>(target) - (site + 5));
		VirtualProtect(p, 5, old, &old);
		FlushInstructionCache(GetCurrentProcess(), p, 5);
		return true;
	}

	void init(HMODULE self)
	{
		char path[MAX_PATH] = {};
		GetModuleFileNameA(nullptr, path, MAX_PATH);
		if (char *slash = strrchr(path, '\\'))
			strcpy_s(slash + 1, MAX_PATH - (slash + 1 - path), "wor_hud_fixes.log");
		fopen_s(&g_log, path, "w");
		log("wor_hud_fixes 1.2 (GH5 / WoR HUD)");
		if (!sites_match())
			return;
		log(install_set_lights() ? "streak lights: patched (WoR colours, x1 pink, own texture names)"
		                         : "streak lights: patch failed (VirtualProtect)");
		const bool sp = install_call(kSpCall1, reinterpret_cast<void *>(&sp_set_texture_hook)) &&
		                install_call(kSpCall2, reinterpret_cast<void *>(&sp_set_texture_hook));
		log(sp ? "star power fill: patched (own texture names)" : "star power fill: patch failed (VirtualProtect)");
		// push ecx; push edi; mov edi, [esp+0xc] = 6 bytes of whole instructions
		g_unload_font = reinterpret_cast<UnloadFontFn>(install_jmp(kUnloadFont, 6, reinterpret_cast<void *>(&unload_font_hook)));
		log(g_unload_font ? "font unload: hooked (bounds fixed on first use)" : "font unload: hook failed");
		(void)self;
	}
}

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID)
{
	if (reason == DLL_PROCESS_ATTACH)
	{
		DisableThreadLibraryCalls(module);
		init(module);
	}
	return TRUE;
}
