"""Writes plugin/src/names.h: the QB checksums of the plugin's light textures (same names as tools/wor_1g.py ships).

usage: python tools/gen_plugin_names.py"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths, wor_1g  # noqa: E402


def qbkey(s):
    """Neversoft QB checksum: CRC-32 (reflected, poly 0xEDB88320, init 0xFFFFFFFF, no final xor) of the lowercase name."""
    c = 0xFFFFFFFF
    for ch in s.lower().encode():
        c ^= ch
        for _ in range(8):
            c = (c >> 1) ^ 0xEDB88320 if c & 1 else c >> 1
    return c


def main():
    rows = [[f'WoR_HUD_light_{st}{c}' for st in range(3)] for c in wor_1g.LIGHT_SETS]
    names = [n for r in rows for n in r]
    assert wor_1g.LIGHT_MARKER in names
    out = ['// generated by tools/gen_plugin_names.py; do not edit', '#pragma once', '#include <cstdint>', '',
           '// [set][state]: sets x1 pink, x2 orange, x3 green, x4 purple, star power blue; states off, half, lit',
           'static const uint32_t kLights[5][3] = {']
    out += ['\t{ ' + ', '.join(f'0x{qbkey(n):08x}' for n in r) + ' },   // ' + ', '.join(r) for r in rows]
    out += ['};', '', 'static const uint32_t kOurLights[] = {']
    out += ['\t' + ', '.join(f'0x{qbkey(n):08x}' for n in r) + ',' for r in rows]
    out += ['};', '']
    out += ['// star power fill: stock name the DE sets -> our name (segments start on the second column)',
            'static const uint32_t kSpFill[][2] = {']
    out += [f'\t{{ 0x{qbkey(a):08x}, 0x{qbkey(b):08x} }},   // {a} -> {b}' for a, b in wor_1g.SP_FILL_NAMES]
    out += ['};', '']
    out += ['// smooth star power fill (tools/wor_1g.py plugin_geometry): canvas units of the band meter desc',
            f'static const uint32_t kSpFull = 0x{qbkey(wor_1g.SP_FULL_NAMES[0]):08x};   // {wor_1g.SP_FULL_NAMES[0]}',
            f'static const uint32_t kSpFullB = 0x{qbkey(wor_1g.SP_FULL_NAMES[1]):08x};  // {wor_1g.SP_FULL_NAMES[1]}']
    out += [f'static const float {k} = {v:.4f}f;' for k, v in wor_1g.plugin_geometry().items()]
    out += ['']
    p = os.path.join(paths.REPO, 'plugin', 'src', 'names.h')
    open(p, 'w', newline='\n').write('\n'.join(out))
    print('wrote', p)


if __name__ == '__main__':
    main()
