"""Writes plugin/src/names.h: the QB checksums of the plugin's light textures (same names as tools/wor_1g.py ships).

usage: python tools/gen_plugin_names.py"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths, wor_1g  # noqa: E402


def qbkey(s):
    """Neversoft QB checksum: CRC-32 (reflected, poly 0xEDB88320, init 0xFFFFFFFF, no final xor) of the lowercase name."""
    c = 0xFFFFFFFF
    for ch in s.lower().encode():
        c ^= ch
        for _ in range(8):
            c = (c >> 1) ^ 0xEDB88320 if c & 1 else c >> 1
    return c


def main():
    rows = [[f'WoR_HUD_light_{st}{c}' for st in range(3)] for c in wor_1g.LIGHT_SETS]
    names = [n for r in rows for n in r]
    assert wor_1g.LIGHT_MARKER in names
    out = ['// generated by tools/gen_plugin_names.py; do not edit', '#pragma once', '#include <cstdint>', '',
           '// [set][state]: sets x1 pink, x2 orange, x3 green, x4 purple, star power blue; states off, half, lit',
           'static const uint32_t kLights[5][3] = {']
    out += ['\t{ ' + ', '.join(f'0x{qbkey(n):08x}' for n in r) + ' },   // ' + ', '.join(r) for r in rows]
    out += ['};', '', 'static const uint32_t kOurLights[] = {']
    out += ['\t' + ', '.join(f'0x{qbkey(n):08x}' for n in r) + ',' for r in rows]
    out += ['};', '']
    out += ['// star power fill: stock name the DE sets -> our name (segments start on the second column)',
            'static const uint32_t kSpFill[][2] = {']
    out += [f'\t{{ 0x{qbkey(a):08x}, 0x{qbkey(b):08x} }},   // {a} -> {b}' for a, b in wor_1g.SP_FILL_NAMES]
    out += ['};', '']
    out += ['// smooth star power fill (tools/wor_1g.py plugin_geometry): canvas units of the band meter desc',
            f'static const uint32_t kSpFull = 0x{qbkey(wor_1g.SP_FULL_NAMES[0]):08x};   // {wor_1g.SP_FULL_NAMES[0]}',
            f'static const uint32_t kSpFullB = 0x{qbkey(wor_1g.SP_FULL_NAMES[1]):08x};  // {wor_1g.SP_FULL_NAMES[1]}',
            f'static const uint32_t kScoreFont = 0x{qbkey(wor_1g.SCORE_FONT):08x};  // {wor_1g.SCORE_FONT}, kept resident']
    out += [f'static const float {k} = {v:.4f}f;' for k, v in wor_1g.plugin_geometry().items()]
    out += ['']
    out += ['// GH5 star power lifecycle (tools/wor_1g.py, docs/GH5_STAR_POWER_REFERENCE.md)',
            f'static const float kPlasmaFps = {wor_1g.SP_PLASMA_FPS:.1f}f;',
            f'static const float kSnap = {wor_1g.SP_SNAP:.3f}f;',
            f'static const float kFeatherH = {wor_1g.SP_FEATHER_H:.2f}f;', f'static const int kFeathers = {len(wor_1g.SP_FEATHER_ALPHA)};',
            f'static const float kBallFps = {wor_1g.SP_BALL_FPS:.1f}f;',
            f'static const float kBurstHold = {wor_1g.SP_BURST_TIME[0]:.3f}f, kBurstEnd = {wor_1g.SP_BURST_TIME[1]:.3f}f;',
            f'static const uint32_t kPlasma[{len(wor_1g.SP_PLASMA_NAMES)}] = {{']
    for i in range(0, len(wor_1g.SP_PLASMA_NAMES), 8):
        out.append('	' + ', '.join(f'0x{qbkey(n):08x}' for n in wor_1g.SP_PLASMA_NAMES[i:i + 8]) + ',')
    out += ['};', f'static const uint32_t kBall[{len(wor_1g.SP_BALL_NAMES)}] = {{']
    for i in range(0, len(wor_1g.SP_BALL_NAMES), 8):
        out.append('	' + ', '.join(f'0x{qbkey(n):08x}' for n in wor_1g.SP_BALL_NAMES[i:i + 8]) + ',')
    out += ['};', '// bottom glow, cap (white), cap (colour): texture names and the alpha each shows at']
    out += ['// star bar / song progress / star glow (tools/wor_1g.py)',
            f'static const uint32_t kStarBar = 0x{qbkey(wor_1g.STAR_BAR_NAME):08x}, kStarLead = 0x{qbkey(wor_1g.STAR_LEAD_NAME):08x};',
            f'static const uint32_t kProgFill = 0x{qbkey(wor_1g.PROG_FILL_NAME):08x}, kProgLead = 0x{qbkey(wor_1g.PROG_LEAD_NAME):08x};',
            f'static const float kCometHead = {wor_1g.COMET_HEAD:.3f}f, kStarLeadS = {wor_1g.STAR_LEAD_S:.3f}f, kProgLeadS = {wor_1g.PROG_LEAD_S:.3f}f;',
            f'static const float kFireFps = {wor_1g.STAR_FIRE_FPS:.1f}f, kFireBase = {wor_1g.STAR_FIRE_ALPHA[0]:.3f}f, kFireAmp = {wor_1g.STAR_FIRE_ALPHA[1]:.3f}f, kFireHz = {wor_1g.STAR_FIRE_ALPHA[2]:.3f}f;',
            f'static const uint32_t kStarFire[{wor_1g.STAR_FIRE_FRAMES}] = {{']
    for i in range(0, wor_1g.STAR_FIRE_FRAMES, 8):
        out.append('	' + ', '.join(f'0x{qbkey(n):08x}' for n in wor_1g.STAR_FIRE_NAMES[i:i + 8]) + ',')
    out += ['};', '']
    out += [f'static const uint32_t kGlowTex[3] = {{ ' + ', '.join(f'0x{qbkey(n):08x}' for n in wor_1g.SP_GLOW_NAMES)
            + ' };   // ' + ', '.join(wor_1g.SP_GLOW_NAMES)]
    out += ['static const float kGlowAlpha[3] = { ' + ', '.join(f'{g[4]:.2f}f' for g in wor_1g.SP_GLOW_SPRITES) + ' };']
    out += ['// burst sprites: canvas offset from the fill top']
    out += ['static const float kBurstOff[3][2] = { ' + ', '.join(f'{{ {o[0]:.1f}f, {o[1]:.1f}f }}' for o, _ in wor_1g.SP_BURST)
            + ' };']
    n = wor_1g.SP_LEVEL_STEPS
    out += [f'// fill-top point on the tube centre line (canvas) for level i / {n}', f'static const int kLevelSteps = {n};',
            f'static const float kLevelPt[{n + 1}][2] = {{']
    pts = [wor_1g.sp_level_point(i / n) for i in range(n + 1)]
    for i in range(0, n + 1, 4):
        out.append('	' + ' '.join(f'{{ {x:.2f}f, {y:.2f}f }},' for x, y in pts[i:i + 4]))
    out += ['};', '']
    p = os.path.join(paths.REPO, 'plugin', 'src', 'names.h')
    open(p, 'w', newline='\n').write('\n'.join(out))
    print('wrote', p)


if __name__ == '__main__':
    main()
